version: '2'
services:
  orderentry2-app:
    image: orderentry2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orderentry2-postgresql:5432/OrderEntry2
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  orderentry2-postgresql:
    extends:
      file: postgresql.yml
      service: orderentry2-postgresql
